<?php

use Illuminate\Database\Seeder;

class CmsLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_logs')->delete();
        
        \DB::table('cms_logs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'admin@crudbooster.com login with IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 09:13:08',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/users/add-save',
                'description' => 'Add New Data admin at Users Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 09:25:58',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'admin@konveksi.com login with IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 09:27:24',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/add-save',
                'description' => 'Add New Data Master Data at Menu Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 09:28:35',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/1',
                'description' => 'Update data Unit at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>parent_id</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 09:28:54',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/units/add-save',
                'description' => 'Add New Data Liter at Unit',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 09:29:20',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'admin@crudbooster.com login with IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:09:20',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'admin@konveksi.com login with IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:11:08',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/1',
                'description' => 'Update data Unit at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>icon</td><td>fa fa-glass</td><td>fa fa-bars</td></tr><tr><td>parent_id</td><td>2</td><td></td></tr><tr><td>sorting</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:12:55',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/3',
                'description' => 'Update data Warna at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>parent_id</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:14:26',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:14:30',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:15:35',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:15:41',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:17:30',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:17:33',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/3',
                'description' => 'Update data Warna at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>parent_id</td><td>2</td><td></td></tr><tr><td>sorting</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:19:15',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:20:10',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:20:26',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/delete/1',
                'description' => 'Delete data Unit at Menu Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:20:41',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/delete/3',
                'description' => 'Delete data Warna at Menu Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:20:45',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/add-save',
                'description' => 'Add New Data Warna at Menu Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:21:14',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/add-save',
                'description' => 'Add New Data Unit at Menu Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:21:36',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:21:46',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:22:13',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'admin@konveksi.com logout',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:22:19',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'admin@konveksi.com login with IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:22:24',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/units',
                'description' => 'Try view the data :name at Unit',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:22:27',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/colors',
                'description' => 'Try view the data :name at Warna',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:22:30',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/6',
                'description' => 'Update data Material Size at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>icon</td><td>fa fa-glass</td><td>fa fa-bars</td></tr><tr><td>sorting</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:26:13',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/module_generator/delete/17',
                'description' => 'Delete data Material at Module Generator',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:34:12',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/module_generator/delete/18',
                'description' => 'Delete data Material at Module Generator',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:35:08',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/delete/10',
                'description' => 'Delete data Material at Menu Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:35:23',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/8',
                'description' => 'Update data Material Unit at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>parent_id</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:35:48',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/7',
                'description' => 'Update data Material Type at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>parent_id</td><td>2</td><td></td></tr><tr><td>sorting</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:35:58',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/edit-save/3',
                'description' => 'Update data Kaos Polos at Material',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>material_size_id</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:43:31',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/edit-save/3',
                'description' => 'Update data Kaos Polos at Material',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>material_size_id</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:43:43',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/add-save',
                'description' => 'Add New Data Testasas at Material',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:44:39',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/delete/2',
                'description' => 'Delete data Sablon at Material',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:47:54',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/statistic_builder/add-save',
                'description' => 'Add New Data Total Material at Statistic Builder',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:48:16',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/statistic_builder/edit-save/1',
                'description' => 'Update data Dashboard Admin at Statistic Builder',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>name</td><td>Total Material</td><td>Dashboard Admin</td></tr><tr><td>slug</td><td>total-material</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:48:41',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'admin@konveksi.com logout',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:52:29',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'admin@konveksi.com login with IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:52:42',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/material_units',
                'description' => 'Try view the data :name at Material Unit',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:52:47',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/material_types',
                'description' => 'Try view the data :name at Material Type',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:52:50',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/material_sizes',
                'description' => 'Try view the data :name at Material Size',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:52:56',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/11',
                'description' => 'Update data Material at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>parent_id</td><td>2</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 13:53:55',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/logout',
                'description' => 'admin@konveksi.com logout',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:57:16',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/login',
                'description' => 'admin@konveksi.com login with IP Address 127.0.0.1',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 13:57:27',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/statistic_builder/edit-save/1',
                'description' => 'Update data Warna at Statistic Builder',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>name</td><td>Dashboard Admin</td><td>Warna</td></tr><tr><td>slug</td><td>total-material</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 14:05:39',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/sizes/edit-save/1',
                'description' => 'Update data L at Ukuran',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 14:42:18',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/13',
                'description' => 'Update data Produk at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>type</td><td>Route</td><td>Module</td></tr><tr><td>path</td><td>AdminProductsControllerGetIndex</td><td>products</td></tr><tr><td>color</td><td></td><td>normal</td></tr><tr><td>icon</td><td>fa fa-glass</td><td>fa fa-shopping-cart</td></tr><tr><td>sorting</td><td>4</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 14:48:14',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/products/add-save',
                'description' => 'Add New Data Nama Produk at Produk',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 14:54:34',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/edit-save/4',
                'description' => 'Update data Testasas at Material',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>stock</td><td>100000</td><td>10</td></tr><tr><td>notify_stock</td><td>0</td><td>20</td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 14:59:34',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/edit-save/3',
                'description' => 'Update data Kaos Polos at Material',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>notify_stock</td><td>0</td><td>80</td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 14:59:55',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/edit-save/3',
                'description' => 'Update data Kaos Polos at Material',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>notify_stock</td><td>80</td><td>20</td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 15:03:34',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/edit-save/3',
                'description' => 'Update data Kaos Polos at Material',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>notify_stock</td><td>20</td><td>90</td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 15:03:45',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/materials/edit-save/3',
                'description' => 'Update data Kaos Polos at Material',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>notify_stock</td><td>90</td><td>95</td></tr></tbody></table>',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 15:04:23',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/statistic_builder/edit-save/1',
                'description' => 'Update data Dashboard Admin at Statistic Builder',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>name</td><td>Warna</td><td>Dashboard Admin</td></tr><tr><td>slug</td><td>total-warna</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 15:17:50',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/add-save',
                'description' => 'Add New Data Dashboard at Menu Management',
                'details' => '',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 15:35:57',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/14',
                'description' => 'Update data Dashboard at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>icon</td><td></td><td></td></tr><tr><td>parent_id</td><td>0</td><td></td></tr><tr><td>is_dashboard</td><td>0</td><td>1</td></tr><tr><td>sorting</td><td></td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 15:36:04',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/12',
                'description' => 'Update data Ukuran at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>color</td><td></td><td>normal</td></tr><tr><td>parent_id</td><td>2</td><td></td></tr><tr><td>sorting</td><td>6</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 15:36:39',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/13',
                'description' => 'Update data Produk at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>sorting</td><td>4</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 15:36:54',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/menu_management/edit-save/13',
                'description' => 'Update data Produk at Menu Management',
                'details' => '<table class="table table-striped"><thead><tr><th>Key</th><th>Old Value</th><th>New Value</th></thead><tbody><tr><td>sorting</td><td>4</td><td></td></tr></tbody></table>',
                'id_cms_users' => 1,
                'created_at' => '2020-10-29 15:36:55',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/sizes',
                'description' => 'Try view the data :name at Ukuran',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 15:38:02',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/sizes',
                'description' => 'Try view the data :name at Ukuran',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 15:38:08',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'ipaddress' => '127.0.0.1',
            'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36',
                'url' => 'http://localhost:8000/admin/products',
                'description' => 'Try view the data :name at Produk',
                'details' => '',
                'id_cms_users' => 2,
                'created_at' => '2020-10-29 15:38:12',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}